[package]
name = "em6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
bytes = "1.4.0"
clap = { version = "4.3.0", features = ["derive"] }
thiserror = "1.0.40"
